name = "mobile_swarm_simulation"
uuid = "45000b25-babc-453d-ac81-a39992bed074"
authors = ["chrisizeh "]
version = "0.1.0"

[deps]
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
